version: '3.8'

services:
  # frontend:
  #   image: node:14
  #   container_name: react_frontend
  #   working_dir: /app
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - "3000:3000"
  #   command: ["npm", "start"]
  #   depends_on:
  #     - backend

  backend:
    container_name: sample_backend_container
    build:
      context: ./sample_backend_container
      dockerfile: Dockerfile
    volumes:
      - ./sample_backend_container:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    working_dir: /app
    ports:
      - 8000:8000
    tty: true
    depends_on:
      - db


  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: sample_db
      POSTGRES_USER: sample_user
      POSTGRES_PASSWORD: sample_password
      TZ: Asia/Tokyo
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # テスト用のDB構築スクリプト
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  postgres_data:


