name: "Setup Docker Environment"
description: "Setup Docker environment with optional database initialization"

inputs:
  db_container_flg:
    description: "Whether to include a database container (true/false)"
    required: true
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Start backend container
      run: |
        docker-compose -f ./docker-compose.yml up -d backend
        echo "Backend container started."

    - name: Start database container (if db_container_flg is true)
      if: ${{ inputs.db_container_flg == 'true' }}
      run: |
        docker-compose -f ./docker-compose.yml up -d db
        echo "Database container started."
