name: Lint and Type Check

on:
  push:
    # branches:
    #   - main
  pull_request:

jobs:
  setup_environment:
    name: Setup Environment with Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Environment
        uses: ./.github/actions/setup-docker/setup-docker-action.yml
        with:
          db_container_flg: "true"

  run_ruff:
    name: Run Ruff
    runs-on: ubuntu-latest
    needs: setup_environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Ruff
        run: |
          poetry run ruff check

  run_mypy:
    name: Run Mypy
    runs-on: ubuntu-latest
    needs: setup_environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Mypy
        run: |
          poetry run mypy .
