"""Modify sample_model2

Revision ID: 69ca849c7c8c
Revises: a1e5f4dc79f9
Create Date: 2024-11-09 13:28:37.232666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69ca849c7c8c'
down_revision: Union[str, None] = 'a1e5f4dc79f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
