"""created_atもれを修正

Revision ID: 6c17bc065515
Revises: 61585b9f8e9d
Create Date: 2024-11-14 05:46:52.512920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c17bc065515'
down_revision: Union[str, None] = '61585b9f8e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_search_history', sa.Column('created_at', sa.TIMESTAMP(), nullable=True, comment='作成日時'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_search_history', 'created_at')
    # ### end Alembic commands ###
