"""Initial migration

Revision ID: 6ed439031384
Revises: 
Create Date: 2024-11-09 12:24:41.810068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed439031384'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sample_table_id'), 'sample_table', ['id'], unique=False)
    op.create_index(op.f('ix_sample_table_name'), 'sample_table', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sample_table_name'), table_name='sample_table')
    op.drop_index(op.f('ix_sample_table_id'), table_name='sample_table')
    op.drop_table('sample_table')
    # ### end Alembic commands ###
