"""created_atもれを修正

Revision ID: 789e212fcb37
Revises: 72954b721905
Create Date: 2024-11-14 05:44:55.795826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '789e212fcb37'
down_revision: Union[str, None] = '72954b721905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag_view_history', sa.Column('created_at', sa.TIMESTAMP(), nullable=True, comment='作成日時'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag_view_history', 'created_at')
    # ### end Alembic commands ###
