"""Modify sample_model


Revision ID: 9495f1990b25
Revises: 3ac605782ecf
Create Date: 2024-11-09 14:09:42.026526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9495f1990b25'
down_revision: Union[str, None] = '3ac605782ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sample_table_id'), 'sample_table', ['id'], unique=False)
    op.create_index(op.f('ix_sample_table_name'), 'sample_table', ['name'], unique=False)
    op.create_table('sample_table2rrrr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['related_id'], ['sample_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sample_table2rrrr_id'), 'sample_table2rrrr', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sample_table2rrrr_id'), table_name='sample_table2rrrr')
    op.drop_table('sample_table2rrrr')
    op.drop_index(op.f('ix_sample_table_name'), table_name='sample_table')
    op.drop_index(op.f('ix_sample_table_id'), table_name='sample_table')
    op.drop_table('sample_table')
    # ### end Alembic commands ###
