"""Modify sample_model aaaa

Revision ID: a1e5f4dc79f9
Revises: 0ab7e02d9eca
Create Date: 2024-11-09 13:26:32.615107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e5f4dc79f9'
down_revision: Union[str, None] = '0ab7e02d9eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_tableaaaa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sample_tableaaaa_id'), 'sample_tableaaaa', ['id'], unique=False)
    op.create_index(op.f('ix_sample_tableaaaa_name'), 'sample_tableaaaa', ['name'], unique=False)
    op.drop_index('ix_sample_table_id', table_name='sample_table')
    op.drop_index('ix_sample_table_name', table_name='sample_table')
    op.drop_table('sample_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sample_table_pkey')
    )
    op.create_index('ix_sample_table_name', 'sample_table', ['name'], unique=False)
    op.create_index('ix_sample_table_id', 'sample_table', ['id'], unique=False)
    op.drop_index(op.f('ix_sample_tableaaaa_name'), table_name='sample_tableaaaa')
    op.drop_index(op.f('ix_sample_tableaaaa_id'), table_name='sample_tableaaaa')
    op.drop_table('sample_tableaaaa')
    # ### end Alembic commands ###
