name: Pytest
 
on:
  pull_request:
  # プルリクエストにプッシュするたびに実行したい場合はtypesをコメントにする
    # types: 
    #   - closed
    # プルリクエストがマージされるときにこのワークフローをトリガーします。
  workflow_dispatch:
    # 手動でこのワークフローをトリガーします。

jobs:
  setup_environment:
    name: Setup Backend and DB Environment
    runs-on: ubuntu-latest
    # ジョブをUbuntu最新環境で実行します。

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # リポジトリのコードをチェックアウトします。
        # これにより、以降のステップでリポジトリの内容にアクセスできます。

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
        # Docker Composeをインストールします。
        # GitHub Actionsの初期環境には含まれていないため、このステップで追加します。

      - name: Set up Backend and DB Containers
        run: |
          docker-compose -f ./docker-compose.yml up -d backend db

  run_pytest:
    name: Run Pytest
    runs-on: ubuntu-latest
    needs: setup_environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Pytest
        run: |
          docker exec sample_backend_container poetry run pytest
        # backendコンテナ内でpytestを実行します。
        # docker execを使用して、コンテナ内部でコマンドを実行しています。
