name: Lint and Type Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint_and_type_check:
    name: Run Ruff and Mypy
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: sample_db
          POSTGRES_USER: sample_user
          POSTGRES_PASSWORD: sample_password
        ports:
          - 5432:5432
        options: >
          --health-cmd "pg_isready -U sample_user -d sample_db" \
          --health-interval 10s \
          --health-timeout 5s \
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      - name: Install dependencies
        run: |
          cd sample_backend_container
          $HOME/.local/bin/poetry install

      - name: Run Ruff
        run: |
          cd sample_backend_container
          $HOME/.local/bin/poetry run ruff check

      - name: Run Mypy
        run: |
          cd sample_backend_container
          $HOME/.local/bin/poetry run mypy .
